name: Build

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build binary
      run: |
        docker build -t builder .
        docker run --rm -v ${PWD}:/project builder make
    - uses: actions/upload-artifact@v4
      with:
       name: DRXUtil
       path: |
         *.rpx
